name: build

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [Win32, x64]
        defines: [standard]
    steps:
    - name: configure
      run: dir && mkdir -p build && cd build && dir && cmake ..
    - name: build
      run: cmake --build . --config Release
    - name: test
      run: build/smmalloc_test.exe
    - name: perftest
      run: build/smmalloc_perf.exe
