name: build

on: [push]

jobs:
  build-unix:
    strategy:
      matrix:
        os: [ubuntu, macos]
        compiler: [g++, clang++]
        defines: [standard]
        exclude:
          - os: macos
            compiler: g++
    name: ${{matrix.os}} ${{matrix.compiler}}
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: CMake Configure
      run: mkdir build && cd build && cmake ..
    - name: Build
      run: cd build && cmake --build . --config Release
    - name: Step1
      run: ls
    - name: Step2
      run: cd build && ls
    - name: Step3
      run: cd build && cd bin && ls
    - name: Step4
      run: cd build && cd bin && ./smmalloc_test
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [Win32, x64]
        defines: [standard]
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: CMake Configure
      run: mkdir build && cd build && cmake ..
    - name: Build
      run: cd build && cmake --build . --config Release
    - name: Run unit tests
      run: "build/Release/smmalloc_test.exe"
    - name: Run performance tests
      run: "build/Release/smmalloc_perf.exe"
